version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: itl-ai-postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - itl_ai_postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: itl-ai-backend

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    command: >
      gunicorn app.main:app
      -k uvicorn.workers.UvicornWorker
      -w 2
      -b 0.0.0.0:8000

volumes:
  itl_ai_postgres_data: